In [6]:
import numpy as np

In [31]:
# Andai kita memiliki daftar data sebagai berikut
daftar = [1, 10, 2, 3, 30, 4, 2, 50]

# Dan kita ingin membuat daftar dari daftar tersebut sedemikian sehingga
# bernilai False jika data di daftar > 10, selainnya True maka
daftar = np.array(daftar)
daftar

array([ 1, 10,  2,  3, 30,  4,  2, 50])

In [32]:
daftar_bool = daftar > 10
daftar_bool

array([False, False, False, False,  True, False, False,  True])

In [22]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
condlist = [x < 3, x > 5]
condlist

[array([ True,  True,  True, False, False, False, False, False, False,
        False]),
 array([False, False, False, False, False, False,  True,  True,  True,
         True])]

In [25]:
x < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [26]:
choicelist = [x, x**2]
choicelist

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])]

In [27]:
x = np.arange(10)

In [28]:
condlist = [x<3, x>5]

In [29]:
choicelist = [x, x**2]

In [30]:
np.select(condlist, choicelist)

array([ 0,  1,  2,  0,  0,  0, 36, 49, 64, 81])